import type { CurriculumItem } from '@/types'

// ---------- Hand-authored curriculum library ----------
// Complete Noorani Qaida, Tajweed guide, Makharij guide, stopping (waqf)
// rules, daily duas and selected hadiths. Every item is read-only content
// that teachers can assign to classes or individual students.

const base = {
  juzNum: null,
  pageFrom: null,
  pageTo: null,
  surahNum: null,
  surahName: null,
  ayahFrom: null,
  ayahTo: null,
  qaidaLesson: null,
  defaultQari: 'ar.alafasy',
} as const

// ================= Noorani Qaida — complete (17 lessons) =================

export const QAIDA_ITEMS: CurriculumItem[] = [
  {
    ...base,
    id: 'qaida-1',
    title: 'Lesson 1 — Isolated Letters (Huruf Mufradat)',
    description: 'Recognition of all 28 Arabic letters in their isolated forms with correct names and sounds.',
    track: 'qaida',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'ا   ب   ت   ث   ج   ح   خ   د   ذ   ر   ز   س   ش   ص   ض   ط   ظ   ع   غ   ف   ق   ك   ل   م   ن   و   هـ   ي',
    contentTranslit:
      'alif, bā, tā, thā, jīm, ḥā, khā, dāl, dhāl, rā, zāy, sīn, shīn, ṣād, ḍād, ṭāʾ, ẓāʾ, ʿayn, ghayn, fā, qāf, kāf, lām, mīm, nūn, wāw, hā, yā',
    contentEn:
      'Point to each letter, say its name, then produce its sound from the correct articulation point. Master this lesson before anything else — every later lesson builds on letter recognition.',
    tajweedRules: ['Letter names', 'Makhraj recognition'],
    qaidaLesson: 1,
  },
  {
    ...base,
    id: 'qaida-2',
    title: 'Lesson 2 — Joined Letter Forms (Huruf Murakkabat)',
    description: 'Reading letters as they appear when joined together in word shapes.',
    track: 'qaida',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'بـتـث  |  جـحـخ  |  دذرزسشص  |  ضطظعغفق  |  كـلـمـن  |  وهـي',
    contentTranslit: 'ba-ta-tha | jim-ḥa-kha | dal-dhal-ra-zay-sin-shin-ṣad | ḍad-ṭa-ẓa-ʿayn-ghayn-fa-qaf | kaf-lam-mim-nun | wa-ha-ya',
    contentEn:
      'Letters change shape at the beginning, middle and end of a word. Read each group left to right in Arabic (right to left on the page), naming every letter in its joined form.',
    tajweedRules: ['Letter forms', 'Joining shapes'],
    qaidaLesson: 2,
  },
  {
    ...base,
    id: 'qaida-3',
    title: 'Lesson 3 — Letters with Fatha',
    description: 'Every letter carrying a fatha — the short open "a" vowel.',
    track: 'qaida',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'أَ  بَ  تَ  ثَ  جَ  حَ  خَ  دَ  ذَ  رَ  زَ  سَ  شَ  صَ  ضَ  طَ  ظَ  عَ  غَ  فَ  قَ  كَ  لَ  مَ  نَ  وَ  هَ  يَ',
    contentTranslit: 'a, ba, ta, tha, ja, ḥa, kha, da, dha, ra, za, sa, sha, ṣa, ḍa, ṭa, ẓa, ʿa, gha, fa, qa, ka, la, ma, na, wa, ha, ya',
    contentEn: 'Keep the fatha short and even — never let it stretch into a long "aa". One crisp beat per letter.',
    tajweedRules: ['Fatha', 'Short vowels'],
    qaidaLesson: 3,
  },
  {
    ...base,
    id: 'qaida-4',
    title: 'Lesson 4 — Fatha Joining Drill',
    description: 'Letters with fatha joined into pairs and triplets — the first real reading.',
    track: 'qaida',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'أَبَ  أَتَ  أَثَ  |  بَتَ  بَثَ  تَثَ  |  جَحَ  حَخَ  خَجَ  |  دَسَ  سَشَ  شَصَ',
    contentTranslit: 'aba, ata, atha | bata, batha, tatha | jaḥa, ḥakha, khaja | dasa, sasha, shasha',
    contentEn: 'Read each cluster in one breath without pausing between letters. Both vowels stay short and equal in length.',
    tajweedRules: ['Fatha', 'Letter joining'],
    qaidaLesson: 4,
  },
  {
    ...base,
    id: 'qaida-5',
    title: 'Lesson 5 — Letters with Kasra',
    description: 'Every letter carrying a kasra — the short "i" vowel.',
    track: 'qaida',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'إِ  بِ  تِ  ثِ  جِ  حِ  خِ  دِ  ذِ  رِ  زِ  سِ  شِ  صِ  ضِ  طِ  ظِ  عِ  غِ  فِ  قِ  كِ  لِ  مِ  نِ  وِ  هِ  يِ',
    contentTranslit: 'i, bi, ti, thi, ji, ḥi, khi, di, dhi, ri, zi, si, shi, ṣi, ḍi, ṭi, ẓi, ʿi, ghi, fi, qi, ki, li, mi, ni, wi, hi, yi',
    contentEn: 'The kasra is a short "i" sound produced with a slight lowering of the jaw. Keep it short — do not slide into "ee".',
    tajweedRules: ['Kasra', 'Short vowels'],
    qaidaLesson: 5,
  },
  {
    ...base,
    id: 'qaida-6',
    title: 'Lesson 6 — Kasra Joining Drill',
    description: 'Letters with kasra joined into pairs and triplets.',
    track: 'qaida',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'إِبِ  إِتِ  إِثِ  |  بِتِ  بِثِ  تِثِ  |  جِحِ  حِخِ  دِسِ  سِشِ',
    contentTranslit: 'ibi, iti, ithi | biti, bithi, tithi | jiḥi, ḥikhi, disi, sishi',
    contentEn: 'Join the letters smoothly in one breath. Mixed drill: the teacher should also call out random pairs for the student to read.',
    tajweedRules: ['Kasra', 'Letter joining'],
    qaidaLesson: 6,
  },
  {
    ...base,
    id: 'qaida-7',
    title: 'Lesson 7 — Letters with Damma',
    description: 'Every letter carrying a damma — the short "u" vowel.',
    track: 'qaida',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'أُ  بُ  تُ  ثُ  جُ  حُ  خُ  دُ  ذُ  رُ  زُ  سُ  شُ  صُ  ضُ  طُ  ظُ  عُ  غُ  فُ  قُ  كُ  لُ  مُ  نُ  وُ  هُ  يُ',
    contentTranslit: 'u, bu, tu, thu, ju, ḥu, khu, du, dhu, ru, zu, su, shu, ṣu, ḍu, ṭu, ẓu, ʿu, ghu, fu, qu, ku, lu, mu, nu, wu, hu, yu',
    contentEn: 'Round the lips lightly for the damma. Keep it a short "u" — never stretch it into "oo" at this stage.',
    tajweedRules: ['Damma', 'Short vowels'],
    qaidaLesson: 7,
  },
  {
    ...base,
    id: 'qaida-8',
    title: 'Lesson 8 — Damma Joining Drill',
    description: 'Letters with damma joined into pairs and triplets.',
    track: 'qaida',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'أُبُ  أُتُ  أُثُ  |  بُتُ  بُثُ  تُثُ  |  جُحُ  حُخُ  دُسُ  سُشُ',
    contentTranslit: 'ubu, utu, uthu | butu, buthu, tuthu | juḥu, ḥukhu, dusu, sushu',
    contentEn: 'Read each cluster in one breath with rounded lips on every damma. Then mix: فُتُ، كُتُبَ-style drills from the teacher.',
    tajweedRules: ['Damma', 'Letter joining'],
    qaidaLesson: 8,
  },
  {
    ...base,
    id: 'qaida-9',
    title: 'Lesson 9 — Letters with Sukoon',
    description: 'The sukoon — stopping the letter with no vowel. First step toward real word building.',
    track: 'qaida',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'أَبْ  أَتْ  أَثْ  |  أَجْ  أَحْ  أَخْ  |  أَدْ  أَذْ  أَرْ  |  أَسْ  أَشْ  أَصْ',
    contentTranslit: 'ab, at, ath | aj, aḥ, akh | ad, adh, ar | as, ash, aṣ',
    contentEn: 'Read the first letter with fatha, then stop crisply on the letter carrying the sukoon. No extra vowel may slip in at the stop.',
    tajweedRules: ['Sukoon', 'Stopping practice'],
    qaidaLesson: 9,
  },
  {
    ...base,
    id: 'qaida-10',
    title: 'Lesson 10 — Sukoon Joining Drill',
    description: 'Two-letter clusters with mixed vowels followed by a sukoon.',
    track: 'qaida',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'أَبَتْ  أَثَبَتْ  |  بَتَجْ  بَتَحْ  |  دَسَمْ  شَغَبْ  |  حَمَدْ  نَقَطْ',
    contentTranslit: 'abat, athabat | bataj, bataḥ | dasam, shaghab | ḥamad, naqaṭ',
    contentEn: 'Three-letter patterns: vowel–vowel–sukoon. This is the shape of most Arabic words, so drill until it is automatic.',
    tajweedRules: ['Sukoon', 'Word patterns'],
    qaidaLesson: 10,
  },
  {
    ...base,
    id: 'qaida-11',
    title: 'Lesson 11 — Shaddah with Fatha',
    description: 'The shaddah: one letter doubled — pronounced as two letters, the first with sukoon.',
    track: 'qaida',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'أَبَّ  أَتَّ  أَثَّ  |  أَجَّ  أَحَّ  أَخَّ  |  أَدَّ  أَذَّ  أَزَّ',
    contentTranslit: 'abba, atta, aththa | ajja, aḥḥa, akhkha | adda, adhha, azza',
    contentEn: 'A shaddah letter = the same letter twice: first with sukoon, second with the vowel. Lean gently on the doubled letter.',
    tajweedRules: ['Shaddah', 'Doubling'],
    qaidaLesson: 11,
  },
  {
    ...base,
    id: 'qaida-12',
    title: 'Lesson 12 — Shaddah with Kasra',
    description: 'Doubled letters carrying kasra.',
    track: 'qaida',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'أَبِّ  أَتِّ  أَثِّ  |  أَجِّ  أَحِّ  أَخِّ  |  أَدِّ  أَذِّ  أَزِّ',
    contentTranslit: 'abbi, atti, aththi | ajji, aḥḥi, akhkhi | addi, adhhi, azzi',
    contentEn: 'Same doubling rule — the second letter now carries the kasra. Watch that the jaw drops slightly for the "i" sound.',
    tajweedRules: ['Shaddah', 'Kasra'],
    qaidaLesson: 12,
  },
  {
    ...base,
    id: 'qaida-13',
    title: 'Lesson 13 — Shaddah with Damma',
    description: 'Doubled letters carrying damma.',
    track: 'qaida',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'أَبُّ  أَتُّ  أَثُّ  |  أَجُّ  أَحُّ  أَخُّ  |  أَدُّ  أَذُّ  أَزُّ',
    contentTranslit: 'abbu, attu, aththu | ajju, aḥḥu, akhkhu | addu, adhhu, azzu',
    contentEn: 'Round the lips for the damma on the second (voweled) letter of the doubled pair.',
    tajweedRules: ['Shaddah', 'Damma'],
    qaidaLesson: 13,
  },
  {
    ...base,
    id: 'qaida-14',
    title: 'Lesson 14 — Shaddah with Sukoon Combinations',
    description: 'Doubled letters that end in sukoon — the stopping case of the shaddah.',
    track: 'qaida',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'أَبَّتْ  أَبَّثْ  |  أَحَّمْ  أَجَّنْ  |  أَمَّسْ  أَكَّلْ  |  حَجَّ  حَجَّتْ',
    contentTranslit: 'abbat, abbatḥ | aḥḥam, ajjan | ammas, akkal | ḥajja, ḥajjat',
    contentEn: 'When a shaddah letter carries sukoon, stop with a firm press on the doubled letter — this is the Qalqala preparation stage.',
    tajweedRules: ['Shaddah', 'Sukoon', 'Stopping practice'],
    qaidaLesson: 14,
  },
  {
    ...base,
    id: 'qaida-15',
    title: 'Lesson 15 — Small Words (Kalimat)',
    description: 'Reading complete short words and Quranic one-word units.',
    track: 'qaida',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'قَدْ  |  مِنْ  |  رَبِّ  |  نُوحٌ  |  هُودٌ  |  لُوطٌ  |  طه  |  يس',
    contentTranslit: 'qad | min | rabb | Nūḥ | Hūd | Lūṭ | Ṭā-Hā | Yā-Sīn',
    contentEn: 'Move from letter drills to real words. Read each word end-to-end, applying sukoon stops and shaddah pressure learned earlier.',
    tajweedRules: ['Word reading', 'Tanween introduction'],
    qaidaLesson: 15,
  },
  {
    ...base,
    id: 'qaida-16',
    title: 'Lesson 16 — Long Words and Tanween',
    description: 'Multi-letter words and the three tanween forms (an, in, un).',
    track: 'qaida',
    difficulty: 'intermediate',
    durationMinutes: 40,
    contentAr: 'الْمُؤْمِنُونَ  |  الْعَالَمِينَ  |  صِرَاطٌ  |  مُسْتَقِيمٌ  |  رَحْمَـٰنٌ  |  رَحِيمٌ',
    contentTranslit: 'al-muʾminūn | al-ʿālamīn | ṣirāṭun | mustaqīmun | raḥmānun | raḥīmun',
    contentEn: 'Tanween is a noon sound hidden in the final vowel: fathatayn, kasratayn, dammatayn. Practice the natural two-beat madd in long words.',
    tajweedRules: ['Tanween', 'Madd Tabii', 'Long words'],
    qaidaLesson: 16,
  },
  {
    ...base,
    id: 'qaida-17',
    title: 'Lesson 17 — Full Ayah Reading Practice',
    description: 'Graduation lesson: reading complete ayahs of the Quran with everything learned.',
    track: 'qaida',
    difficulty: 'intermediate',
    durationMinutes: 40,
    contentAr: 'بِسْمِ اللَّهِ الرَّحْمَـٰنِ الرَّحِيمِ ﴿١﴾ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ﴿٢﴾ وَقُل رَّبِّ زِدْنِي عِلْمًا',
    contentTranslit: 'Bismillāhir-raḥmānir-raḥīm. Al-ḥamdu lillāhi rabbil-ʿālamīn. Wa qul rabbi zidnī ʿilmā.',
    contentEn:
      'Read whole ayahs fluently: correct letters, short vowels, sukoon stops, shaddah pressure and tanween. Passing this lesson moves the student into the Quran proper.',
    tajweedRules: ['Fluency', 'All Qaida rules combined'],
    qaidaLesson: 17,
  },
]

// ================= Complete Tajweed Guide =================

export const TAJWEED_ITEMS: CurriculumItem[] = [
  {
    ...base,
    id: 'taj-1',
    title: 'Tajweed 1 — Introduction: What Is Tajweed?',
    description: 'Definition, virtue and ruling of reciting the Quran with tajweed.',
    track: 'tajweed',
    difficulty: 'beginner',
    durationMinutes: 25,
    contentAr: 'وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا',
    contentTranslit: 'Wa rattilil-Qurʾāna tartīlā',
    contentEn:
      'Tajweed means giving every letter its right and its due — its articulation point (makhraj) and its characteristics (sifat), and observing the rules that apply when letters meet. Learning the rules is a communal obligation; applying them in recitation is an individual obligation. "And recite the Quran with measured recitation." (Al-Muzzammil 73:4)',
    tajweedRules: ['Definition', 'Ruling of tajweed'],
  },
  {
    ...base,
    id: 'taj-2',
    title: 'Tajweed 2 — Noon Sakinah and Tanween: The Four Rules',
    description: 'Overview of what happens when a saakin noon or tanween meets the next letter.',
    track: 'tajweed',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'مِنْ هَادٍ  |  مَنْ يَقُولُ  |  مِنْ بَعْدِ  |  مِنْ قَبْلُ',
    contentTranslit: 'min hādin | man yaqūlu | min baʿdi | min qablu',
    contentEn:
      'A noon sakinah (نْ) or tanween (ـً ـٍ ـٌ) meeting the next letter produces one of four rules: Izhar (clear pronunciation), Idgham (merging), Iqlab (conversion to meem), or Ikhfa (hiding). The next four lessons cover each in full.',
    tajweedRules: ['Noon sakinah', 'Tanween'],
  },
  {
    ...base,
    id: 'taj-3',
    title: 'Tajweed 3 — Al-Izhar Al-Halqi',
    description: 'Clear pronunciation of the noon before the six throat letters.',
    track: 'tajweed',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'مِنْ هَادٍ   يَنْحِتُونَ   مِنْ عِلْمٍ   مِنْ غِلٍّ   مَنْ خَلَقَ',
    contentTranslit: 'min hādin | yanḥitūna | min ʿilmin | min ghillin | man khalaqa',
    contentEn:
      'If a noon sakinah or tanween is followed by one of the six throat letters — ء ه ع ح غ خ — the noon is pronounced clearly with no ghunnah prolongation and no merging.',
    tajweedRules: ['Izhar', 'Throat letters'],
  },
  {
    ...base,
    id: 'taj-4',
    title: 'Tajweed 4 — Al-Idgham (With and Without Ghunnah)',
    description: 'Merging the noon into the following letter — ي ن م و (with ghunnah), ل ر (without).',
    track: 'tajweed',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'مَنْ يَعْمَلْ   مِنْ وَلِيٍّ   مِنْ مَاءٍ   مِنْ نُورٍ   مِنْ لَّدُنْهُ   مِنْ رَّبِّهِمْ',
    contentTranslit: 'man yaʿmal | min waliyyin | min māʾin | min nūr | mil-ladunhu | mir-rabbihim',
    contentEn:
      'Before the letters gathered in the word يَرْمَلُون the noon merges into the next letter. With ي ن م و the merge carries a 2-beat ghunnah; with ل and ر it merges completely without ghunnah. Idgham only occurs between two words, never inside one word.',
    tajweedRules: ['Idgham with Ghunnah', 'Idgham bila Ghunnah'],
  },
  {
    ...base,
    id: 'taj-5',
    title: 'Tajweed 5 — Al-Iqlab',
    description: 'Converting the noon into a hidden meem before the letter ba.',
    track: 'tajweed',
    difficulty: 'intermediate',
    durationMinutes: 30,
    contentAr: 'مِنْ بَعْدِ   أَنْبِئْهُمْ   سَمِيعٌ بَصِيرٌ',
    contentTranslit: 'mim baʿdi | ambiʾhum | samīʿun baṣīr',
    contentEn:
      'When a noon sakinah or tanween is followed by ب, the noon is converted into a meem sound that is hidden with a 2-beat ghunnah before pronouncing the ba.',
    tajweedRules: ['Iqlab', 'Ghunnah'],
  },
  {
    ...base,
    id: 'taj-6',
    title: 'Tajweed 6 — Al-Ikhfa Al-Haqiqi',
    description: 'Hiding the noon with ghunnah before the remaining 15 letters.',
    track: 'tajweed',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'مِنْ قَبْلُ   أَنْتُمْ   مِنْ ثَمَرَةٍ   يَنْصُرُكُمْ   مِنْ سَلَـٰمٍ',
    contentTranslit: 'min qablu | antum | min thamaratin | yanṣurukum | min salāmin',
    contentEn:
      'Before any of the 15 remaining letters (ت ث ج د ذ ز س ش ص ض ط ظ ف ق ك), the noon is pronounced between izhar and idgham — hidden through the nose with a 2-beat ghunnah. This is the most frequent noon rule in the Quran.',
    tajweedRules: ['Ikhfa Haqiqi', 'Ghunnah'],
  },
  {
    ...base,
    id: 'taj-7',
    title: 'Tajweed 7 — Rules of Meem Sakinah',
    description: 'The three rules when a saakin meem meets the next letter.',
    track: 'tajweed',
    difficulty: 'intermediate',
    durationMinutes: 30,
    contentAr: 'تَرْمِيهِم بِحِجَارَةٍ   لَهُمْ مَّا يَشَاءُونَ   هُمْ فِيهَا خَالِدُونَ',
    contentTranslit: 'tarmīhim bi-ḥijāratin | lahum mā yashāʾūn | hum fīhā khālidūn',
    contentEn:
      'Meem sakinah + م = Idgham Shafawi (merge with 2-beat ghunnah). Meem sakinah + ب = Ikhfa Shafawi (hide the meem at the lips with ghunnah). Meem sakinah + any other letter = Izhar Shafawi (pronounce clearly, guarding especially against hiding before و and ف).',
    tajweedRules: ['Idgham Shafawi', 'Ikhfa Shafawi', 'Izhar Shafawi'],
  },
  {
    ...base,
    id: 'taj-8',
    title: 'Tajweed 8 — Al-Ghunnah',
    description: 'The nasal sound inherent in noon and meem — its amount and places.',
    track: 'tajweed',
    difficulty: 'beginner',
    durationMinutes: 25,
    contentAr: 'إِنَّ   ثُمَّ   الْجَنَّةِ   عَمَّ',
    contentTranslit: 'inna | thumma | al-jannati | ʿamma',
    contentEn:
      'Ghunnah is a pleasant nasal sound residing in ن and م. It is completed in two counts (harakahs) when the letter carries a shaddah, and accompanies Ikhfa, Iqlab and the ghunnah-forms of Idgham.',
    tajweedRules: ['Ghunnah', 'Two counts'],
  },
  {
    ...base,
    id: 'taj-9',
    title: 'Tajweed 9 — Al-Qalqalah',
    description: 'The echoing bounce on ق ط ب ج د when they carry sukoon.',
    track: 'tajweed',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'يَدْخُلُونَ   قُرِئَ   الْفَلَقِ   مِن قَبْلُ   مُحِيط',
    contentTranslit: 'yadkhulūna | quriʾa | al-falaq | min qablu | muḥīṭ',
    contentEn:
      'The letters ق ط ب ج د (gathered in قُطْبُ جَدٍّ) produce a bouncing echo when they carry sukoon: Qalqalah Sughra (small) in the middle of a word, Qalqalah Kubra (stronger) when stopping on them.',
    tajweedRules: ['Qalqala Sughra', 'Qalqala Kubra'],
  },
  {
    ...base,
    id: 'taj-10',
    title: 'Tajweed 10 — Al-Madd Al-Asli (Tabii)',
    description: 'The natural madd — 2 counts — and its three letters.',
    track: 'tajweed',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'قَالُوا   يَقُولُ   قِيلَ   نُوحِيهَا',
    contentTranslit: 'qālū | yaqūlu | qīla | nūḥīhā',
    contentEn:
      'The madd letters are ا (after fatha), و (after damma), ي (after kasra). When no hamzah or sukoon follows, the madd is natural and lasts exactly 2 counts — no more, no less.',
    tajweedRules: ['Madd Tabii'],
  },
  {
    ...base,
    id: 'taj-11',
    title: 'Tajweed 11 — Secondary Madds: Muttasil, Munfasil, Arid, Lin, Badal',
    description: 'The five main secondary madds and their lengths.',
    track: 'tajweed',
    difficulty: 'advanced',
    durationMinutes: 45,
    contentAr: 'جَاءَ   بِمَا أُنزِلَ   الْعَالَمِينَ (وقف)   خَوْفٌ   آمَنُوا',
    contentTranslit: 'jāʾa | bimā unzila | al-ʿālamīn (stop) | khawfun | āmanū',
    contentEn:
      'Muttasil (madd + hamzah in one word): 4–5 counts. Munfasil (madd + hamzah in the next word): 2–4–5 counts. Arid lis-sukun (stopping after a madd): 2, 4 or 6. Lin (stopping after وْ or يْ preceded by fatha): 2, 4 or 6. Badal (hamzah before a madd letter): 2 counts.',
    tajweedRules: ['Madd Muttasil', 'Madd Munfasil', 'Madd Arid Lissukoon', 'Madd Lin', 'Madd Badal'],
  },
  {
    ...base,
    id: 'taj-12',
    title: 'Tajweed 12 — Madd Lazim and Madd Silah',
    description: 'The obligatory 6-count madd and the madd of the pronoun هاء.',
    track: 'tajweed',
    difficulty: 'advanced',
    durationMinutes: 40,
    contentAr: 'الضَّالِّينَ   الْحَاقَّةُ   الم   لَهُ مَا فِي السَّمَاوَاتِ',
    contentTranslit: 'aḍ-ḍāllīn | al-ḥāqqah | Alif-Lām-Mīm | lahū mā fis-samāwāt',
    contentEn:
      'Madd Lazim (madd followed by an original sukoon or shaddah, in a word or in the opening letters) is always 6 counts. Madd Silah: the detached pronoun هاء/هاء is prolonged 2 counts (Sughra) — and 4–5 counts if followed by hamzah (Kubra).',
    tajweedRules: ['Madd Lazim', 'Madd Sila'],
  },
  {
    ...base,
    id: 'taj-13',
    title: 'Tajweed 13 — Rules of Lam: Jalalah, Shamsiyyah and Qamariyyah',
    description: 'The lam of the name Allah and the lam of the definite article.',
    track: 'tajweed',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'اللَّهِ   لِلَّهِ   الشَّمْسُ   الْقَمَرُ',
    contentTranslit: 'Allāhi | lillāhi | ash-shamsu | al-qamaru',
    contentEn:
      'The lam of Allah is heavy (tafkheem) after fatha/damma and light (tarqeeq) after kasra. With the definite article: before the 14 solar letters the lam is assimilated (ash-Shams), and before the 14 lunar letters it is pronounced clearly (al-Qamar).',
    tajweedRules: ['Lam Shamsiyyah', 'Lam Qamariyyah', 'Lam of Jalalah'],
  },
  {
    ...base,
    id: 'taj-14',
    title: 'Tajweed 14 — Rules of Ra',
    description: 'When ra is heavy (tafkheem) and when it is light (tarqeeq).',
    track: 'tajweed',
    difficulty: 'advanced',
    durationMinutes: 40,
    contentAr: 'رَبِّ   رِزْقٌ   الْأَبْرَارِ   الْقَدْرِ   فِرْقٌ',
    contentTranslit: 'rabbi | rizqun | al-abrār | al-qadr | firq',
    contentEn:
      'Ra is heavy: with fatha/damma, when saakin after fatha/damma, or when saakin after kasra followed by a heavy letter. Ra is light: with kasra, when saakin after an original kasra (not followed by a heavy letter), or when stopping on it after a saakin ya. Two special words allow both: فِرْق and مِصْر when stopping.',
    tajweedRules: ['Tafkheem of Ra', 'Tarqeeq of Ra'],
  },
  {
    ...base,
    id: 'taj-15',
    title: 'Tajweed 15 — Small Idghams: Mithlayn, Mutajanisayn, Mutaqaribayn',
    description: 'Merging identical, homogeneous and neighboring letters.',
    track: 'tajweed',
    difficulty: 'advanced',
    durationMinutes: 40,
    contentAr: 'اضْرِب بِّعَصَاكَ   اذْهَب بِّكِتَابِي   قَدْ تَبَيَّنَ   بَل رَّفَعَهُ',
    contentTranslit: 'iḍrib bi-ʿaṣāka | idhhab bi-kitābī | qat-tabayyana | bar-rafaʿahu',
    contentEn:
      'Mithlayn: two identical letters, first saakin (ب + ب). Mutajanisayn: same makhraj, different sifat (ط-د-ت, ذ-ظ-ث, م-ب). Mutaqaribayn: close in makhraj and sifat (ق-ك, ل-ر). When the first of the pair is saakin, it merges into the second.',
    tajweedRules: ['Idgham Mithlayn', 'Idgham Mutajanisayn', 'Idgham Mutaqaribayn'],
  },
  {
    ...base,
    id: 'taj-16',
    title: 'Tajweed 16 — Tafkheem and Tarqeeq of Letters',
    description: 'Which letters are always heavy, always light, and which vary.',
    track: 'tajweed',
    difficulty: 'advanced',
    durationMinutes: 40,
    contentAr: 'خُذِ الْعَفْوَ   اللَّهُ الصَّمَدُ   مُسْتَقِيمٌ',
    contentTranslit: 'khudhil-ʿafwa | Allāhuṣ-ṣamad | mustaqīm',
    contentEn:
      'Always heavy: the seven letters خ ص ض غ ط ق ظ, plus the lam of Allah after fatha/damma and ra per its rules. Always light: all remaining letters. The lam of Allah and ra are the two letters whose weight changes with context.',
    tajweedRules: ['Tafkheem', 'Tarqeeq'],
  },
]

// ================= Complete Makharij Guide =================

export const MAKHARIJ_ITEMS: CurriculumItem[] = [
  {
    ...base,
    id: 'makh-1',
    title: 'Makharij 1 — Introduction to the Articulation Points',
    description: 'What a makhraj is, and the five general areas of the 17 points.',
    track: 'makharij',
    difficulty: 'beginner',
    durationMinutes: 25,
    contentAr: 'الْمَخَارِجُ الْعَامَّةُ خَمْسَة: الْجَوْف، الْحَلْق، اللِّسَان، الشَّفَتَان، الْخَيْشُوم',
    contentTranslit: 'al-makhārijul-ʿāmmah khamsah: al-jawf, al-ḥalq, al-lisān, ash-shafatān, al-khayshūm',
    contentEn:
      'A makhraj is the exact place where a letter\'s sound is born. There are five general areas containing seventeen specific points: the empty space of the mouth and throat (al-Jawf), the throat (al-Halq), the tongue (al-Lisan), the two lips (ash-Shafatan) and the nasal passage (al-Khayshum). Every letter has exactly one home.',
    tajweedRules: ['Five general areas', '17 specific points'],
  },
  {
    ...base,
    id: 'makh-2',
    title: 'Makharij 2 — Al-Jawf: The Empty Space',
    description: 'The three madd letters born from the empty space of mouth and throat.',
    track: 'makharij',
    difficulty: 'beginner',
    durationMinutes: 25,
    contentAr: 'ا   و   ي',
    contentTranslit: 'alif (aa), waw (uu), ya (ii)',
    contentEn:
      'From the empty space (al-Jawf) come the three madd letters: alif preceded by fatha, waw saakinah preceded by damma, and ya saakinah preceded by kasra. Their sound travels through the open cavity and ends with the breath.',
    tajweedRules: ['Al-Jawf', 'Madd letters'],
  },
  {
    ...base,
    id: 'makh-3',
    title: 'Makharij 3 — Al-Halq: The Throat',
    description: 'Six letters from three points of the throat — lower, middle, upper.',
    track: 'makharij',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'ء هـ   |   ع ح   |   غ خ',
    contentTranslit: 'hamzah, hā (lower throat) | ʿayn, ḥā (middle throat) | ghayn, khā (upper throat)',
    contentEn:
      'Lower throat (nearest the chest): ء and هـ. Middle throat: ع and ح. Upper throat (nearest the mouth): غ and خ. These are the izhar letters — and the hardest for non-Arabs, especially the difference between ح and هـ, and between ع and ء.',
    tajweedRules: ['Throat letters', 'Izhar letters'],
  },
  {
    ...base,
    id: 'makh-4',
    title: 'Makharij 4 — Al-Lisan: The Tongue',
    description: 'Ten points of the tongue producing eighteen letters — the largest group.',
    track: 'makharij',
    difficulty: 'intermediate',
    durationMinutes: 45,
    contentAr: 'ق ك | ج ش ي | ض | ل | ن | ر | ط د ت | ص ز س | ظ ذ ث',
    contentTranslit:
      'qaf, kaf (back of tongue) | jim, shin, ya (middle) | dad (one edge) | lam (other edge-tip) | nun (tip below lam) | ra (behind nun) | ta, dal, ta (tip) | sad, zay, sin (front-edge) | dha, dhal, tha (very tip)',
    contentEn:
      'The tongue carries ten of the seventeen points. Back: ق then ك. Middle: ج ش ي. Edges: ض from one edge (the hardest letter), ل from the tip-edge. Tip: ن then ر slightly behind it, then ط د ت from the very tip, then ص ز س from the front edge with the teeth, then ظ ذ ث from the extreme tip against the upper front teeth.',
    tajweedRules: ['Tongue points', 'Dad vs Zha', 'Letter precision'],
  },
  {
    ...base,
    id: 'makh-5',
    title: 'Makharij 5 — Ash-Shafatan: The Two Lips',
    description: 'Four letters produced by the lips.',
    track: 'makharij',
    difficulty: 'beginner',
    durationMinutes: 25,
    contentAr: 'ف   ب   م   و',
    contentTranslit: 'fā (lower lip + upper teeth) | bā, mīm (both lips closed) | wāw (lips rounded and open)',
    contentEn:
      'Fa comes from the inner lower lip touching the edges of the upper front teeth. Ba and meem from closing both lips (meem accompanies them with ghunnah through the nose). Waw from rounded, parted lips. Never turn fa into a "v" sound or let ba pop with an extra vowel.',
    tajweedRules: ['Lip letters', 'Izhar Shafawi connection'],
  },
  {
    ...base,
    id: 'makh-6',
    title: 'Makharij 6 — Al-Khayshum: The Nasal Passage',
    description: 'The home of the ghunnah sound.',
    track: 'makharij',
    difficulty: 'beginner',
    durationMinutes: 20,
    contentAr: 'إِنَّ   ثُمَّ   مِنْ قَبْلُ',
    contentTranslit: 'inna | thumma | min qablu',
    contentEn:
      'The nasal passage (al-Khayshum) is the makhraj of the ghunnah that accompanies noon and meem shaddah, ikhfa, iqlab and idgham-with-ghunnah. Test it: pinch the nose while saying the sound — it should be blocked.',
    tajweedRules: ['Ghunnah', 'Nasal passage'],
  },
  {
    ...base,
    id: 'makh-7',
    title: 'Makharij 7 — The Complete Chart of 17 Points',
    description: 'All seventeen articulation points and their letters in one reference.',
    track: 'makharij',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: '١ الْجَوْف: ا و ي — ٢-٤ الْحَلْق: ء هـ، ع ح، غ خ — ٥-١٤ اللِّسَان: ق، ك، ج، ش، ي، ض، ل، ن، ر، ط د ت، ص ز س، ظ ذ ث — ١٥-١٦ الشَّفَتَان: ف، ب م و — ١٧ الْخَيْشُوم: الْغُنَّة',
    contentTranslit: '1: al-Jawf (a, w, y) | 2–4: throat (hamzah/ha, ain/ha, ghain/kha) | 5–14: tongue (q, k, j, sh, y, dad, l, n, r, t-d-t, s-z-s, z-dh-th) | 15–16: lips (f, b-m-w) | 17: khayshum (ghunnah)',
    contentEn:
      'Memorize this chart: 1 general space (3 letters), 3 throat points (6 letters), 10 tongue points (18 letters), 2 lip points (4 letters), 1 nasal passage. Drilling order: throat first, then the tongue pairs students confuse most (ض/ظ, ح/هـ, ع/ء, ق/ك).',
    tajweedRules: ['Full chart', 'Confused pairs'],
  },
  {
    ...base,
    id: 'makh-8',
    title: 'Makharij 8 — Common Mistakes and Cures',
    description: 'Practical drills for the letters most often mispronounced.',
    track: 'makharij',
    difficulty: 'intermediate',
    durationMinutes: 40,
    contentAr: 'ضَالِّينَ / ظَالِّينَ — حَمْدٌ / هَمْدٌ — عِلْمٌ / إِلْمٌ — قَلْبٌ / كَلْبٌ',
    contentTranslit: 'ḍāllīn / ẓāllīn — ḥamdun / hamdun — ʿilmun / ilmūn — qalbun / kalbun',
    contentEn:
      'ض is from the tongue edge and must never become ظ (tongue tip) — "ḍāllīn" and "ẓāllīn" are two different words. ح must rasp from the mid-throat, not soften into هـ. ع must press from the mid-throat, not collapse into a glottal stop. ق is deeper and heavier than ك. Drill each pair slowly, then in words, then in ayahs.',
    tajweedRules: ['Dad vs Zha', 'Ha vs Ha', 'Ain vs Hamzah', 'Qaf vs Kaf'],
  },
]

// ================= Stopping Rules (Waqf & Ibtida) =================

export const WAQF_ITEMS: CurriculumItem[] = [
  {
    ...base,
    id: 'waqf-1',
    title: 'Waqf 1 — Introduction and the Three Kinds of Stopping',
    description: 'Why waqf matters and the classification of stops.',
    track: 'waqf',
    difficulty: 'beginner',
    durationMinutes: 30,
    contentAr: 'الْوَقْفُ الاِخْتِيَارِي — الاِضْطِرَارِي — الاِخْتِبَارِي',
    contentTranslit: 'al-waqful-ikhtiyārī — al-iḍṭirārī — al-ikhtibārī',
    contentEn:
      'Waqf is cutting the voice at the end of a word for a breath, with the intention of resuming. Ikhtiyari: the reciter chooses the stop by choice (this is where the rules apply). Idtirari: forced by need — coughing, running out of breath; it is excused. Ikhtibari: stopping to teach or test a word. The Prophet (peace be upon him) would stop at the end of each ayah.',
    tajweedRules: ['Kinds of waqf'],
  },
  {
    ...base,
    id: 'waqf-2',
    title: 'Waqf 2 — The Four Categories of a Chosen Stop',
    description: 'Tam, Kafi, Hasan and Qabih — and when each is allowed.',
    track: 'waqf',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ (تام) — الم ذَلِكَ الْكِتَابُ (كافٍ)',
    contentTranslit: 'al-ḥamdu lillāhi rabbil-ʿālamīn (tam) | Alif-Lām-Mīm, dhālikal-kitāb (kāfī)',
    contentEn:
      'Tam (complete): stopping where nothing after depends on what before — best. Kafi (sufficient): meaning is complete but a grammatical link remains. Hasan (good): meaning is complete but the word after is closely linked in meaning — do not resume from it. Qabih (offensive): stopping where meaning breaks or misleads — forbidden deliberately, e.g. stopping on "لا" of negation.',
    tajweedRules: ['Tam', 'Kafi', 'Hasan', 'Qabih'],
  },
  {
    ...base,
    id: 'waqf-3',
    title: 'Waqf 3 — The Waqf Symbols in the Mushaf',
    description: 'Every stop sign printed in the standard mushaf and what it commands.',
    track: 'waqf',
    difficulty: 'beginner',
    durationMinutes: 35,
    contentAr: 'م   ط   ج   ز   ص   ق   لا   ﴿﴾',
    contentTranslit:
      'mīm (mandatory) | ṭā (preferred) | jīm (permissible) | zāy (permitted, stopping better) | ṣād (licensed) | qāf (qila — some said stop) | lā (do not stop) | kissing-stops ﴿﴾',
    contentEn:
      'م: obligatory stop — stopping is required. ط: preferred stop. ج: both stopping and continuing are acceptable. ز / ص: stopping is permitted (better than continuing). ق: some scholars recommended the stop. لا: do not stop here (except at end of ayah). ﴿﴾: two marks mean stop at only one of them — never both, never neither.',
    tajweedRules: ['Waqf signs', 'Mushaf symbols'],
  },
  {
    ...base,
    id: 'waqf-4',
    title: 'Waqf 4 — Stopping on Ta Marbutah',
    description: 'The ة becomes a clear ha when stopping.',
    track: 'waqf',
    difficulty: 'beginner',
    durationMinutes: 25,
    contentAr: 'رَحْمَةٌ → رَحْمَهْ   الْجَنَّةُ → الْجَنَّهْ   نِعْمَتُ → نِعْمَهْ',
    contentTranslit: 'raḥmah → raḥmah | al-jannatu → al-jannah',
    contentEn:
      'When you stop on a word ending in ة (ta marbutah), it is pronounced as a clear ه with sukoon. Continuing resumes the ta. Drill: رَحْمَةٌ، جَنَّةٌ، نِعْمَةٌ — stop and continue each three times.',
    tajweedRules: ['Ta marbutah', 'Stopping form'],
  },
  {
    ...base,
    id: 'waqf-5',
    title: 'Waqf 5 — Stopping on Tanween, Madd and Sukoon Words',
    description: 'How the word changes at the stop.',
    track: 'waqf',
    difficulty: 'intermediate',
    durationMinutes: 35,
    contentAr: 'عَلِيمٌ → عَلِيمْ   هُدًى → هُدَا   الْفَلَقِ (قلقلة)   يُوسُفُ (عارض)',
    contentTranslit: 'ʿalīmun → ʿalīm | hudan → hudā | al-falaq (qalqalah) | yūsufu (arid)',
    contentEn:
      'Tanween with fatha becomes a one-beat alif at the stop (except after ة). Tanween with kasra/damma drops to plain sukoon. Madd arid lis-sukun appears when stopping on a word whose last letter is voweled: 2, 4 or 6 counts. Qalqalah letters are bounced at the stop.',
    tajweedRules: ['Tanween stopping', 'Madd Arid Lissukoon', 'Qalqala Kubra'],
  },
  {
    ...base,
    id: 'waqf-6',
    title: 'Waqf 6 — Ibtida: The Rules of Resuming',
    description: 'Where you may start again after a stop.',
    track: 'waqf',
    difficulty: 'advanced',
    durationMinutes: 35,
    contentAr: 'وَقَالَتِ الْيَهُودُ — (begin from وَ or from قَالَتِ?)',
    contentTranslit: 'wa-qālatil-yahūdu — resume from the connected phrase',
    contentEn:
      'After a chosen stop, resume (ibtida) from a place that gives complete meaning — usually from the beginning of the sentence or phrase, not from the exact word stopped on. If you stop mid-phrase by necessity, go back to before it. Never resume from a word that distorts the meaning.',
    tajweedRules: ['Ibtida', 'Resuming correctly'],
  },
  {
    ...base,
    id: 'waqf-7',
    title: 'Waqf 7 — Full Practice: Fatiha and Baqarah Opening',
    description: 'Applying stops and resumes to real recitation.',
    track: 'waqf',
    difficulty: 'intermediate',
    durationMinutes: 40,
    contentAr: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ﴿٢﴾ (وقف ط) الرَّحْمَـٰنِ الرَّحِيمِ ﴿٣﴾ — ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ (وقف ج)',
    contentTranslit: 'al-ḥamdu lillāhi rabbil-ʿālamīn (stop ṭā) | ar-raḥmānir-raḥīm | dhālikal-kitābu lā rayba fīh (stop jīm)',
    contentEn:
      'Recite Al-Fatiha stopping on every ayah end, then the opening of Al-Baqarah honoring the small symbols (ۛ means two stops of equal rank — stop at one). The teacher marks each stop as tam/kafi/hasan and corrects any qabih stop.',
    tajweedRules: ['Applied waqf', 'Stop-and-resume drill'],
  },
]

// ================= Daily Duas =================

export const DUAS_ITEMS: CurriculumItem[] = [
  {
    ...base,
    id: 'dua-1',
    title: 'Dua Before Sleeping',
    description: 'The supplication recited when going to sleep.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    contentTranslit: 'Bismika Allāhumma amūtu wa aḥyā',
    contentEn: 'In Your name, O Allah, I die and I live. (Bukhari 6324, Muslim 2711)',
    tajweedRules: ['Short dua', 'Madd Tabii'],
  },
  {
    ...base,
    id: 'dua-2',
    title: 'Dua Upon Waking Up',
    description: 'The supplication recited upon waking from sleep.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    contentTranslit: 'Al-ḥamdu lillāhil-ladhī aḥyānā baʿda mā amātanā wa ilayhin-nushūr',
    contentEn: 'All praise is for Allah who gave us life after having taken it from us, and unto Him is the resurrection. (Bukhari 6312, Muslim 2711)',
    tajweedRules: ['Idgham with Ghunnah', 'Lam Shamsiyyah'],
  },
  {
    ...base,
    id: 'dua-3',
    title: 'Dua Before Eating',
    description: 'Saying Bismillah before the meal — and what to say if you forget.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'بِسْمِ اللَّهِ — وَإِنْ نَسِيَ: بِسْمِ اللَّهِ فِي أَوَّلِهِ وَآخِرِهِ',
    contentTranslit: 'Bismillāh — and if forgotten: Bismillāhi fī awwalihī wa ākhirih',
    contentEn: 'In the name of Allah. If one forgets at the beginning, he says: In the name of Allah at its beginning and its end. (Abu Dawud 3767, Tirmidhi 1858)',
    tajweedRules: ['Lam Shamsiyyah', 'Madd Sila'],
  },
  {
    ...base,
    id: 'dua-4',
    title: 'Dua After Eating',
    description: 'Gratitude after finishing the meal.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    contentTranslit: 'Al-ḥamdu lillāhil-ladhī aṭʿamanā wa saqānā wa jaʿalanā muslimīn',
    contentEn: 'All praise is for Allah who fed us, gave us drink and made us Muslims. (Abu Dawud 3850, Tirmidhi 3451)',
    tajweedRules: ['Idgham with Ghunnah', 'Madd Tabii'],
  },
  {
    ...base,
    id: 'dua-5',
    title: 'Dua When Leaving the House',
    description: 'Protection when stepping out of the home.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    contentTranslit: 'Bismillāh, tawakkaltu ʿalallāh, wa lā ḥawla wa lā quwwata illā billāh',
    contentEn: 'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah. (Abu Dawud 5095, Tirmidhi 3426)',
    tajweedRules: ['Qalqala Kubra', 'Madd Badal'],
  },
  {
    ...base,
    id: 'dua-6',
    title: 'Dua When Entering the Masjid',
    description: 'Asking for Allah’s mercy upon entering the mosque.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    contentTranslit: 'Allāhumma-ftaḥ lī abwāba raḥmatik',
    contentEn: 'O Allah, open for me the doors of Your mercy. (Muslim 713)',
    tajweedRules: ['Shaddah', 'Qalqala Sughra'],
  },
  {
    ...base,
    id: 'dua-7',
    title: 'Dua When Leaving the Masjid',
    description: 'Asking for Allah’s bounty upon leaving the mosque.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    contentTranslit: 'Allāhumma innī asʾaluka min faḍlik',
    contentEn: 'O Allah, I ask You from Your bounty. (Muslim 713)',
    tajweedRules: ['Ghunnah', 'Ikhfa Haqiqi'],
  },
  {
    ...base,
    id: 'dua-8',
    title: 'Dua for Knowledge',
    description: 'The Quranic supplication for increase in knowledge.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'رَبِّ زِدْنِي عِلْمًا',
    contentTranslit: 'Rabbi zidnī ʿilmā',
    contentEn: 'My Lord, increase me in knowledge. (Taha 20:114)',
    tajweedRules: ['Qalqala Sughra', 'Tanween stopping'],
  },
  {
    ...base,
    id: 'dua-9',
    title: 'Dua for Parents',
    description: 'The Quranic supplication for one’s parents.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    contentTranslit: 'Rabbi-rḥamhumā kamā rabbayānī ṣagīrā',
    contentEn: 'My Lord, have mercy upon them (my parents) as they brought me up when I was small. (Al-Isra 17:24)',
    tajweedRules: ['Madd Tabii', 'Qalqala Sughra'],
  },
  {
    ...base,
    id: 'dua-10',
    title: 'Dua Before Entering the Toilet',
    description: 'Seeking refuge before entering.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
    contentTranslit: 'Allāhumma innī aʿūdhu bika minal-khubuthi wal-khabāʾith',
    contentEn: 'O Allah, I seek refuge in You from the male and female devils. (Bukhari 142, Muslim 375)',
    tajweedRules: ['Izhar Halqi', 'Lam Qamariyyah'],
  },
  {
    ...base,
    id: 'dua-11',
    title: 'Dua After Wudu',
    description: 'The testimony and supplication after completing ablution.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'أَشْهَدُ أَنْ لَا إِلَـٰهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ، اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ',
    contentTranslit:
      'Ash-hadu an lā ilāha illallāh, wa ash-hadu anna Muḥammadan ʿabduhū wa rasūluh. Allāhummaj-ʿalnī minat-tawwābīna waj-ʿalnī minal-mutaṭahhirīn',
    contentEn:
      'I bear witness that none has the right to be worshipped but Allah, and that Muhammad is His servant and Messenger. O Allah, make me among those who repent and those who purify themselves. (Muslim 234, Tirmidhi 55)',
    tajweedRules: ['Idgham bila Ghunnah', 'Ghunnah', 'Madd Sila'],
  },
  {
    ...base,
    id: 'dua-12',
    title: 'Dua for Travel',
    description: 'The supplication for riding and journeying.',
    track: 'duas',
    difficulty: 'intermediate',
    durationMinutes: 15,
    contentAr: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَـٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ',
    contentTranslit: 'Subḥānal-ladhī sakhkhara lanā hādhā wa mā kunnā lahū muqrinīn, wa innā ilā rabbinā lamunqalibūn',
    contentEn: 'Glory be to Him who has subjected this to us, and we could never have it by our efforts; and indeed, to our Lord we will return. (Az-Zukhruf 43:13–14, Muslim 1342)',
    tajweedRules: ['Ikhfa Haqiqi', 'Madd Arid Lissukoon'],
  },
  {
    ...base,
    id: 'dua-13',
    title: 'Morning Dhikr',
    description: 'The opening remembrance of the morning.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَـٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    contentTranslit: 'Aṣbaḥnā wa aṣbaḥal-mulku lillāh, wal-ḥamdu lillāh, lā ilāha illallāhu waḥdahū lā sharīka lah',
    contentEn: 'We have entered the morning and the dominion belongs to Allah. All praise is for Allah. None has the right to be worshipped but Allah alone, without partner. (Muslim 2723)',
    tajweedRules: ['Qalqala Kubra', 'Lam Shamsiyyah'],
  },
  {
    ...base,
    id: 'dua-14',
    title: 'Evening Dhikr',
    description: 'The opening remembrance of the evening.',
    track: 'duas',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَـٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    contentTranslit: 'Amsaynā wa amsal-mulku lillāh, wal-ḥamdu lillāh, lā ilāha illallāhu waḥdahū lā sharīka lah',
    contentEn: 'We have entered the evening and the dominion belongs to Allah. All praise is for Allah. None has the right to be worshipped but Allah alone, without partner. (Muslim 2723)',
    tajweedRules: ['Qalqala Kubra', 'Lam Shamsiyyah'],
  },
  {
    ...base,
    id: 'dua-15',
    title: 'Sayyid al-Istighfar',
    description: 'The master supplication for seeking forgiveness.',
    track: 'duas',
    difficulty: 'advanced',
    durationMinutes: 20,
    contentAr:
      'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَـٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    contentTranslit:
      'Allāhumma anta rabbī lā ilāha illā ant, khalaqtanī wa ana ʿabduk, wa ana ʿalā ʿahdika wa waʿdika mastataʿt, aʿūdhu bika min sharri mā ṣanaʿt, abūʾu laka bi-niʿmatika ʿalay, wa abūʾu bi-dhanbī faghfir lī fa-innahū lā yaghfirudh-dhunūba illā ant',
    contentEn:
      'O Allah, You are my Lord; there is no god but You. You created me and I am Your servant, keeping my covenant and promise with You as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me, and I acknowledge my sin — so forgive me, for none forgives sins but You. (Bukhari 6306) Whoever says it in the morning or evening with conviction and dies that day or night enters Paradise.',
    tajweedRules: ['Ikhfa Haqiqi', 'Ghunnah', 'Qalqala'],
  },
  {
    ...base,
    id: 'dua-16',
    title: 'Dua for Distress and Anxiety',
    description: 'The supplication of the Prophet (peace be upon him) in hardship.',
    track: 'duas',
    difficulty: 'intermediate',
    durationMinutes: 15,
    contentAr: 'لَا إِلَـٰهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَـٰهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ، لَا إِلَـٰهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الْأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ',
    contentTranslit:
      'Lā ilāha illallāhul-ʿaẓīmul-ḥalīm, lā ilāha illallāhu rabbul-ʿarshil-ʿaẓīm, lā ilāha illallāhu rabbu-samāwāti wa rabbul-arḍi wa rabbul-ʿarshil-karīm',
    contentEn:
      'There is no god but Allah, the Forbearing, the Mighty. There is no god but Allah, Lord of the Mighty Throne. There is no god but Allah, Lord of the heavens, Lord of the earth, Lord of the Noble Throne. (Bukhari 6346, Muslim 2730) — the dua of distress.',
    tajweedRules: ['Lam Shamsiyyah', 'Lam Qamariyyah', 'Madd Arid Lissukoon'],
  },
]

// ================= Selected Hadiths =================

export const HADITH_ITEMS: CurriculumItem[] = [
  {
    ...base,
    id: 'had-1',
    title: 'Hadith 1 — The Best of You',
    description: 'On learning the Quran and teaching it.',
    track: 'hadith',
    difficulty: 'beginner',
    durationMinutes: 15,
    contentAr: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
    contentTranslit: 'Khayrukum man taʿallamal-Qurʾāna wa ʿallamah',
    contentEn: 'The best of you is the one who learns the Quran and teaches it. (Bukhari 5027)',
    tajweedRules: ['Madd Tabii', 'Qalqala Sughra'],
  },
  {
    ...base,
    id: 'had-2',
    title: 'Hadith 2 — Actions Are by Intentions',
    description: 'The foundation hadith of sincerity.',
    track: 'hadith',
    difficulty: 'beginner',
    durationMinutes: 15,
    contentAr: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى',
    contentTranslit: 'Innamal-aʿmālu bin-niyyāt, wa innamā li-kulli-mriʾin mā nawā',
    contentEn: 'Actions are only by intentions, and every person will have only what they intended. (Bukhari 1, Muslim 1907)',
    tajweedRules: ['Ghunnah', 'Idgham with Ghunnah'],
  },
  {
    ...base,
    id: 'had-3',
    title: 'Hadith 3 — The Path of Knowledge',
    description: 'Allah makes the path to Paradise easy for the seeker of knowledge.',
    track: 'hadith',
    difficulty: 'intermediate',
    durationMinutes: 15,
    contentAr: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ',
    contentTranslit: 'Man salaka ṭarīqan yaltamisu fīhi ʿilman sahhala-llāhu lahū bihi ṭarīqan ilal-jannah',
    contentEn: 'Whoever travels a path in search of knowledge, Allah will make easy for him a path to Paradise. (Muslim 2699)',
    tajweedRules: ['Ikhfa Haqiqi', 'Lam Shamsiyyah'],
  },
  {
    ...base,
    id: 'had-4',
    title: 'Hadith 4 — Mercy to the Merciful',
    description: 'Show mercy to those on earth.',
    track: 'hadith',
    difficulty: 'beginner',
    durationMinutes: 15,
    contentAr: 'الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَـٰنُ، ارْحَمُوا مَنْ فِي الْأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ',
    contentTranslit: 'Ar-rāḥimūna yarḥamuhumur-Raḥmān, irḥamū man fil-arḍi yarḥamkum man fis-samāʾ',
    contentEn: 'The merciful are shown mercy by the Most Merciful. Show mercy to those on earth, and the One above the heavens will show mercy to you. (Tirmidhi 1924, Abu Dawud 4941)',
    tajweedRules: ['Madd Tabii', 'Lam Shamsiyyah'],
  },
  {
    ...base,
    id: 'had-5',
    title: 'Hadith 5 — The True Muslim',
    description: 'Safety of people from one’s tongue and hand.',
    track: 'hadith',
    difficulty: 'beginner',
    durationMinutes: 15,
    contentAr: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ',
    contentTranslit: 'Al-muslimu man salimal-muslimūna min lisānihī wa yadih',
    contentEn: 'The Muslim is the one from whose tongue and hand the Muslims are safe. (Bukhari 10, Muslim 40)',
    tajweedRules: ['Idgham bila Ghunnah', 'Madd Sila'],
  },
  {
    ...base,
    id: 'had-6',
    title: 'Hadith 6 — Loving for Your Brother',
    description: 'The sign of complete faith.',
    track: 'hadith',
    difficulty: 'beginner',
    durationMinutes: 15,
    contentAr: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّىٰ يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
    contentTranslit: 'Lā yuʾminu aḥadukum ḥattā yuḥibba li-akhīhi mā yuḥibbu li-nafsih',
    contentEn: 'None of you truly believes until he loves for his brother what he loves for himself. (Bukhari 13, Muslim 45)',
    tajweedRules: ['Madd Tabii', 'Qalqala Sughra'],
  },
  {
    ...base,
    id: 'had-7',
    title: 'Hadith 7 — Speak Good or Stay Silent',
    description: 'From the perfection of faith in Allah and the Last Day.',
    track: 'hadith',
    difficulty: 'beginner',
    durationMinutes: 15,
    contentAr: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    contentTranslit: 'Man kāna yuʾminu billāhi wal-yawmil-ākhiri falyaqul khayran aw li-yaṣmut',
    contentEn: 'Whoever believes in Allah and the Last Day, let him speak good or remain silent. (Bukhari 6018, Muslim 47)',
    tajweedRules: ['Qalqala Kubra', 'Lam Qamariyyah'],
  },
  {
    ...base,
    id: 'had-8',
    title: 'Hadith 8 — Do Not Become Angry',
    description: 'The concise advice repeated three times.',
    track: 'hadith',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'لَا تَغْضَبْ',
    contentTranslit: 'Lā taghḍab',
    contentEn: 'A man said to the Prophet (peace be upon him): Advise me. He said: Do not become angry. The man repeated his request several times, and each time he said: Do not become angry. (Bukhari 6116)',
    tajweedRules: ['Qalqala Kubra', 'Sukoon stopping'],
  },
  {
    ...base,
    id: 'had-9',
    title: 'Hadith 9 — Cleanliness Is Half of Faith',
    description: 'The status of purification in Islam.',
    track: 'hadith',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'الطُّهُورُ شَطْرُ الْإِيمَانِ',
    contentTranslit: 'Aṭ-ṭuhūru shaṭrul-īmān',
    contentEn: 'Cleanliness is half of faith. (Muslim 223)',
    tajweedRules: ['Lam Shamsiyyah', 'Madd Badal'],
  },
  {
    ...base,
    id: 'had-10',
    title: 'Hadith 10 — The Quran as Intercessor',
    description: 'The Quran will come on the Day of Judgment for its people.',
    track: 'hadith',
    difficulty: 'beginner',
    durationMinutes: 15,
    contentAr: 'اقْرَءُوا الْقُرْآنَ فَإِنَّهُ يَأْتِي يَوْمَ الْقِيَامَةِ شَفِيعًا لِأَصْحَابِهِ',
    contentTranslit: 'Iqraʾul-Qurʾāna fa-innahū yaʾtī yawmal-qiyāmati shafīʿan li-aṣḥābih',
    contentEn: 'Recite the Quran, for it will come on the Day of Resurrection as an intercessor for its companions. (Muslim 804)',
    tajweedRules: ['Madd Tabii', 'Tanween stopping'],
  },
  {
    ...base,
    id: 'had-11',
    title: 'Hadith 11 — Mercy to the Young, Respect to the Old',
    description: 'The etiquette of the Muslim community.',
    track: 'hadith',
    difficulty: 'beginner',
    durationMinutes: 15,
    contentAr: 'لَيْسَ مِنَّا مَنْ لَمْ يَرْحَمْ صَغِيرَنَا وَيُوَقِّرْ كَبِيرَنَا',
    contentTranslit: 'Laysa minnā man lam yarḥam ṣaghīranā wa yuwaqqir kabīranā',
    contentEn: 'He is not one of us who does not show mercy to our young and respect to our elders. (Tirmidhi 1919)',
    tajweedRules: ['Idgham bila Ghunnah', 'Ghunnah'],
  },
  {
    ...base,
    id: 'had-12',
    title: 'Hadith 12 — Make Things Easy',
    description: 'The prophetic method in teaching and dealing with people.',
    track: 'hadith',
    difficulty: 'beginner',
    durationMinutes: 10,
    contentAr: 'يَسِّرُوا وَلَا تُعَسِّرُوا، وَبَشِّرُوا وَلَا تُنَفِّرُوا',
    contentTranslit: 'Yassirū wa lā tuʿassirū, wa bashshirū wa lā tunaffirū',
    contentEn: 'Make things easy and do not make them difficult; give glad tidings and do not drive people away. (Bukhari 69, Muslim 1734)',
    tajweedRules: ['Shaddah', 'Madd Tabii'],
  },
]

// Everything combined — the complete non-Quran library
export const CONTENT_ITEMS: CurriculumItem[] = [
  ...QAIDA_ITEMS,
  ...TAJWEED_ITEMS,
  ...MAKHARIJ_ITEMS,
  ...WAQF_ITEMS,
  ...DUAS_ITEMS,
  ...HADITH_ITEMS,
]
