import { ReactNode, createContext, useContext, useState } from 'react'
import { addDays, format } from 'date-fns'
import { CLASSES, ENROLL_REQUESTS, LESSONS, STUDENTS, UNIT_TOTALS, today } from '@/lib/mockData'
import type { ClassLevel, ClassRoom, EnrollRequest, LearningTrack, PaceUnit, SessionEndpoint, SessionMistake, SessionScore, StartTrack, Student } from '@/lib/mockData'
import { TEACHER } from '@/lib/mockData'
import type { AvailabilitySlot, LessonAssignment, LessonRubricScore, SlotBooking, SlotGenerationConfig, TeacherSettingsState } from '@/types'

export type Lesson = typeof LESSONS[number]
function estimateCompletion(unitsRemaining: number, quantity: number): string { const daily = Math.max(quantity, 0.1); return format(addDays(today, Math.max(1, Math.ceil(unitsRemaining / daily))), 'yyyy-MM-dd') }
interface NewClassInput { name: string; description: string; level: ClassLevel; learningTrack: LearningTrack }
interface NewEnrollRequestInput { name: string; email: string; preferredTime: string; startTrack: StartTrack; startJuz: number | null; experience: string }
export interface AttendanceRecord { status: 'present' | 'absent' | 'late'; markedAt: number; reason?: string; studentId?: string }
export interface ScheduledSession { id: string; classId: string; className: string; date: string; time: string; duration: number; lessonTitle: string; meetUrl: string; studentName?: string }
export const DEFAULT_TEACHER_SETTINGS: TeacherSettingsState = { institutionName: TEACHER.institution, bio: TEACHER.bio, phone: '+92 300 1234567', timezone: TEACHER.timezone, avatarUrl: null, verificationStatus: 'verified', verifiedDate: '2025-01-12', dailyReportTime: '18:00', reportsEnabled: true, weeklySummaries: true, alertPerformanceDrop: true, alertLowAttendance: false, reminderBeforeSession: true, achievementNotifications: true, language: 'en', theme: 'light', enabledTracks: ['juz_based', 'qaida', 'surah_based', 'tajweed', 'makharij', 'waqf', 'duas', 'hadith'], leaderboardEnabled: true, leaderboardVisibleToStudents: true, mfaEnabled: false }
const TIMEZONES = ['UTC','Asia/Karachi','Asia/Riyadh','Asia/Dubai','Europe/London','America/New_York','America/Toronto','Australia/Sydney']; export { TIMEZONES }
interface AppStoreValue {
 students: Student[]; classes: ClassRoom[]; enrollRequests: EnrollRequest[]; lessons: Lesson[]
 getStudent: (id: string) => Student | undefined; getClass: (id: string) => ClassRoom | undefined; getEnrolledStudents: (classId: string) => Student[]
 updateStudentPace: (studentId: string, quantity: number, unit: PaceUnit) => void; createClass: (data: NewClassInput) => void; archiveClass: (classId: string) => void; restoreClass: (classId: string) => void; enrollStudent: (studentId: string, classId: string | null) => void
 submitEnrollRequest: (data: NewEnrollRequestInput) => void; approveEnrollRequest: (requestId: string) => void; rejectEnrollRequest: (requestId: string) => void
 addLesson: (lesson: Lesson) => void; updateLesson: (lessonId: string, patch: Partial<Lesson>) => void; deleteLesson: (lessonId: string) => void
 scheduledSessions: ScheduledSession[]; addSession: (data: Omit<ScheduledSession, 'id'>) => void
 sessionStarts: Record<string, number>; startSessionTimer: (sessionId: string) => void; sessionEnds: Record<string, number>; endSession: (sessionId: string) => void
 sessionAttendance: Record<string, AttendanceRecord>; markAttendance: (sessionId: string, status: 'present' | 'absent' | 'late', studentId?: string, reason?: string) => void
 sessionMistakes: Record<string, SessionMistake[]>; addMistake: (sessionId: string, mistake: Omit<SessionMistake, 'id' | 'markedAt'>) => void; removeMistake: (sessionId: string, mistakeId: string) => void
 sessionEndpoints: Record<string, SessionEndpoint>; saveEndpoint: (sessionId: string, endpoint: Omit<SessionEndpoint, 'markedAt'>) => void
 sessionScores: Record<string, SessionScore>; submitScore: (sessionId: string, score: Omit<SessionScore, 'submittedAt'>) => void
 lessonAssignments: LessonAssignment[]; assignCurriculum: (data: Omit<LessonAssignment, 'id' | 'assignedAt'>) => void
 lessonProgress: Record<string, number>; saveLessonProgress: (assignmentId: string, lines: number) => void; completeLesson: (assignmentId: string) => void
 teacherNotes: Record<string, string>; updateTeacherNotes: (studentId: string, notes: string) => void
 teacherSettings: TeacherSettingsState; updateTeacherSettings: (patch: Partial<TeacherSettingsState>) => void
 availabilitySlots: AvailabilitySlot[]; generateSlots: (config: SlotGenerationConfig) => number; updateSlot: (slotId: string, patch: Partial<AvailabilitySlot>) => void; setAllSlotsStatus: (status: 'open' | 'closed') => void
 slotBookings: SlotBooking[]; updateBookingStatus: (bookingId: string, status: SlotBooking['status']) => void
 sessionRubrics: Record<string, LessonRubricScore>; saveRubric: (sessionId: string, score: Omit<LessonRubricScore, 'savedAt'>) => void
 reportResends: Record<string, number>; markReportResent: (reportId: string) => void
}
const AppStoreContext = createContext<AppStoreValue | undefined>(undefined)
export function AppStoreProvider({ children }: { children: ReactNode }) {
 const [students, setStudents] = useState<Student[]>(STUDENTS); const [classes, setClasses] = useState<ClassRoom[]>(CLASSES); const [enrollRequests, setEnrollRequests] = useState<EnrollRequest[]>(ENROLL_REQUESTS); const [lessons, setLessons] = useState<Lesson[]>(LESSONS)
 const [scheduledSessions, setScheduledSessions] = useState<ScheduledSession[]>([]); const [sessionStarts, setSessionStarts] = useState<Record<string, number>>({}); const [sessionEnds, setSessionEnds] = useState<Record<string, number>>({}); const [sessionAttendance, setSessionAttendance] = useState<Record<string, AttendanceRecord>>({}); const [sessionMistakes, setSessionMistakes] = useState<Record<string, SessionMistake[]>>({}); const [sessionEndpoints, setSessionEndpoints] = useState<Record<string, SessionEndpoint>>({}); const [sessionScores, setSessionScores] = useState<Record<string, SessionScore>>({})
 const [lessonAssignments, setLessonAssignments] = useState<LessonAssignment[]>([]); const [lessonProgress, setLessonProgress] = useState<Record<string, number>>({}); const [teacherNotes, setTeacherNotes] = useState<Record<string, string>>({}); const [teacherSettings, setTeacherSettings] = useState<TeacherSettingsState>(DEFAULT_TEACHER_SETTINGS); const [availabilitySlots, setAvailabilitySlots] = useState<AvailabilitySlot[]>([]); const [slotBookings, setSlotBookings] = useState<SlotBooking[]>([]); const [sessionRubrics, setSessionRubrics] = useState<Record<string, LessonRubricScore>>({}); const [reportResends, setReportResends] = useState<Record<string, number>>({})
 const getStudent = (id: string) => students.find((s) => s.id === id); const getClass = (id: string) => classes.find((c) => c.id === id); const getEnrolledStudents = (classId: string) => students.filter((s) => s.classId === classId)
 const updateStudentPace = (studentId: string, quantity: number, unit: PaceUnit) => setStudents((prev) => prev.map((s) => { if (s.id !== studentId) return s; const totalUnits = UNIT_TOTALS[unit]; const unitsCompleted = Math.min(Math.round((s.totalUnits > 0 ? s.unitsCompleted / s.totalUnits : 0) * totalUnits), totalUnits); return { ...s, pace: { quantity, unit }, totalUnits, unitsCompleted, estimatedCompletion: estimateCompletion(totalUnits - unitsCompleted, quantity) } }))
 const createClass = (data: NewClassInput) => setClasses((prev) => [...prev, { id: `class-${Date.now()}`, status: 'active', leaderboardEnabled: true, ...data }]); const archiveClass = (classId: string) => setClasses((prev) => prev.map((c) => c.id === classId ? { ...c, status: 'archived' } : c)); const restoreClass = (classId: string) => setClasses((prev) => prev.map((c) => c.id === classId ? { ...c, status: 'active' } : c))
 const enrollStudent = (studentId: string, classId: string | null) => setStudents((prev) => prev.map((s) => s.id === studentId ? { ...s, classId } : s))
 const submitEnrollRequest = (data: NewEnrollRequestInput) => setEnrollRequests((prev) => [{ id: `req-${Date.now()}`, submittedAt: format(today, 'yyyy-MM-dd'), status: 'pending', ...data }, ...prev])
 const approveEnrollRequest = (requestId: string) => { const request = enrollRequests.find((r) => r.id === requestId); if (!request || request.status !== 'pending') return; setEnrollRequests((prev) => prev.map((r) => r.id === requestId ? { ...r, status: 'approved' } : r)); const pagesPerJuz = Math.round(UNIT_TOTALS.pages / 30); const unitsCompleted = request.startTrack === 'juz' && request.startJuz ? (request.startJuz - 1) * pagesPerJuz : 0; setStudents((prev) => [...prev, { id: `student-${Date.now()}`, name: request.name, email: request.email, classId: null, pace: { quantity: 1, unit: 'pages' }, unitsCompleted, totalUnits: UNIT_TOTALS.pages, startDate: format(today, 'yyyy-MM-dd'), estimatedCompletion: estimateCompletion(UNIT_TOTALS.pages - unitsCompleted, 1), status: 'active', streak: 0, points: 0, avgScore: 0, rank: 0 }]) }
 const rejectEnrollRequest = (requestId: string) => setEnrollRequests((prev) => prev.map((r) => r.id === requestId ? { ...r, status: 'rejected' } : r))
 const addLesson = (lesson: Lesson) => setLessons((prev) => [lesson, ...prev.filter((item) => item.id !== lesson.id)]); const updateLesson = (lessonId: string, patch: Partial<Lesson>) => setLessons((prev) => prev.map((lesson) => lesson.id === lessonId ? { ...lesson, ...patch } : lesson)); const deleteLesson = (lessonId: string) => setLessons((prev) => prev.filter((lesson) => lesson.id !== lessonId))
 const addSession = (data: Omit<ScheduledSession, 'id'>) => setScheduledSessions((prev) => [...prev, { ...data, id: `scheduled-${Date.now()}` }])
 const startSessionTimer = (sessionId: string) => setSessionStarts((prev) => prev[sessionId] ? prev : { ...prev, [sessionId]: Date.now() }); const endSession = (sessionId: string) => setSessionEnds((prev) => prev[sessionId] ? prev : { ...prev, [sessionId]: Date.now() })
 const markAttendance = (sessionId: string, status: 'present' | 'absent' | 'late', studentId?: string, reason?: string) => setSessionAttendance((prev) => ({ ...prev, [studentId ? `${sessionId}:${studentId}` : sessionId]: { status, markedAt: Date.now(), studentId, reason } }))
 const addMistake = (sessionId: string, mistake: Omit<SessionMistake, 'id' | 'markedAt'>) => setSessionMistakes((prev) => { const list = prev[sessionId] ?? []; const filtered = list.filter((m) => !(m.verseKey === mistake.verseKey && m.wordPosition === mistake.wordPosition)); return { ...prev, [sessionId]: [...filtered, { ...mistake, id: `mst-${Date.now()}`, markedAt: Date.now() }] } }); const removeMistake = (sessionId: string, mistakeId: string) => setSessionMistakes((prev) => ({ ...prev, [sessionId]: (prev[sessionId] ?? []).filter((m) => m.id !== mistakeId) }))
 const saveEndpoint = (sessionId: string, endpoint: Omit<SessionEndpoint, 'markedAt'>) => setSessionEndpoints((prev) => ({ ...prev, [sessionId]: { ...endpoint, markedAt: Date.now() } })); const submitScore = (sessionId: string, score: Omit<SessionScore, 'submittedAt'>) => setSessionScores((prev) => ({ ...prev, [sessionId]: { ...score, submittedAt: Date.now() } }))
 const assignCurriculum = (data: Omit<LessonAssignment, 'id' | 'assignedAt'>) => setLessonAssignments((prev) => [{ ...data, id: `assign-${Date.now()}`, assignedAt: Date.now() }, ...prev]); const saveLessonProgress = (assignmentId: string, lines: number) => setLessonProgress((prev) => ({ ...prev, [assignmentId]: Math.max(0, Math.min(16, lines)) })); const completeLesson = (assignmentId: string) => setLessonProgress((prev) => ({ ...prev, [assignmentId]: 16 }))
 const updateTeacherNotes = (studentId: string, notes: string) => setTeacherNotes((prev) => ({ ...prev, [studentId]: notes })); const updateTeacherSettings = (patch: Partial<TeacherSettingsState>) => setTeacherSettings((prev) => ({ ...prev, ...patch }))
 const generateSlots = (config: SlotGenerationConfig): number => { const slots: AvailabilitySlot[] = []; const [sh, sm] = config.startTime.split(':').map(Number); const [eh, em] = config.endTime.split(':').map(Number); const startMin = (sh || 0) * 60 + (sm || 0); const endMin = (eh || 0) * 60 + (em || 0); for (let d = 1; d <= 7; d++) { const date = addDays(today, d); if (!config.days.includes(date.getDay())) continue; for (let m = startMin; m + config.slotDuration <= endMin; m += config.slotDuration) { const fmt = (mins: number) => `${String(Math.floor(mins / 60)).padStart(2, '0')}:${String(mins % 60).padStart(2, '0')}`; slots.push({ id: `slot-${format(date, 'yyyyMMdd')}-${m}`, date: format(date, 'yyyy-MM-dd'), start: fmt(m), end: fmt(m + config.slotDuration), maxStudents: 3, enrolledCount: 0, status: 'open' }) } } const bookings: SlotBooking[] = []; students.filter((s) => s.status === 'active').slice(0, Math.min(4, slots.length)).forEach((student, i) => { const slot = slots[i]; if (!slot) return; slot.enrolledCount += 1; bookings.push({ id: `booking-${slot.id}-${student.id}`, slotId: slot.id, studentId: student.id, status: i % 2 === 0 ? 'pending' : 'approved' }) }); slots.forEach((s) => { if (s.enrolledCount >= s.maxStudents) s.status = 'full' }); setAvailabilitySlots(slots); setSlotBookings(bookings); return slots.length }
 const updateSlot = (slotId: string, patch: Partial<AvailabilitySlot>) => setAvailabilitySlots((prev) => prev.map((s) => s.id === slotId ? { ...s, ...patch } : s)); const setAllSlotsStatus = (status: 'open' | 'closed') => setAvailabilitySlots((prev) => prev.map((s) => ({ ...s, status: status === 'open' && s.enrolledCount >= s.maxStudents ? 'full' : status }))); const updateBookingStatus = (bookingId: string, status: SlotBooking['status']) => setSlotBookings((prev) => prev.map((b) => b.id === bookingId ? { ...b, status } : b))
 const saveRubric = (sessionId: string, score: Omit<LessonRubricScore, 'savedAt'>) => setSessionRubrics((prev) => ({ ...prev, [sessionId]: { ...score, savedAt: Date.now() } })); const markReportResent = (reportId: string) => setReportResends((prev) => ({ ...prev, [reportId]: Date.now() }))
 return <AppStoreContext.Provider value={{ students, classes, enrollRequests, lessons, getStudent, getClass, getEnrolledStudents, updateStudentPace, createClass, archiveClass, restoreClass, enrollStudent, submitEnrollRequest, approveEnrollRequest, rejectEnrollRequest, addLesson, updateLesson, deleteLesson, scheduledSessions, addSession, sessionStarts, startSessionTimer, sessionEnds, endSession, sessionAttendance, markAttendance, sessionMistakes, addMistake, removeMistake, sessionEndpoints, saveEndpoint, sessionScores, submitScore, lessonAssignments, assignCurriculum, lessonProgress, saveLessonProgress, completeLesson, teacherNotes, updateTeacherNotes, teacherSettings, updateTeacherSettings, availabilitySlots, generateSlots, updateSlot, setAllSlotsStatus, slotBookings, updateBookingStatus, sessionRubrics, saveRubric, reportResends, markReportResent }}>{children}</AppStoreContext.Provider>
}
export function useAppStore() { const ctx = useContext(AppStoreContext); if (!ctx) throw new Error('useAppStore must be used within AppStoreProvider'); return ctx }
