import { Flame, Trophy, ArrowRight, CalendarDays, BookOpen } from 'lucide-react'
import { Card, CardTitle, CardContent } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { CURRENT_STUDENT, WEEK_SCORES, MILESTONES } from '@/lib/mockData'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'
import { useNavigate } from 'react-router-dom'

export function StudentDashboard() {
 const navigate=useNavigate(); const quranComplete=Math.round((CURRENT_STUDENT.unitsCompleted/CURRENT_STUDENT.totalUnits)*100); const milestones=MILESTONES.filter(m=>m.percentage>quranComplete).slice(0,3)
 return <div className="space-y-6"><div><h1 className="font-display text-2xl font-semibold text-ink">Assalamu alaikum, {CURRENT_STUDENT.name}</h1><p className="mt-1 text-sm text-ink/55">{CURRENT_STUDENT.className} • {CURRENT_STUDENT.teacherName}</p></div>
 <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-4"><Card><CardContent><div className="font-display text-3xl font-semibold">{CURRENT_STUDENT.avgScore}%</div><p className="text-sm text-ink/50">Your average</p></CardContent></Card><Card><CardContent><Flame className="h-6 w-6 text-clay-600"/><div className="font-display text-3xl font-semibold text-green-700">{CURRENT_STUDENT.streak}</div><p className="text-sm text-ink/50">Day streak</p></CardContent></Card><Card><CardContent><div className="font-display text-3xl font-semibold">{quranComplete}%</div><p className="text-sm text-ink/50">Quran complete</p></CardContent></Card><Card><CardContent><Trophy className="h-6 w-6 text-gold-600"/><div className="font-display text-3xl font-semibold">{CURRENT_STUDENT.points}</div><p className="text-sm text-ink/50">Points • Rank #{CURRENT_STUDENT.rank}</p></CardContent></Card></div>
 <Card className="border-green-200 bg-green-50/40"><CardContent className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-green-100 text-green-700"><BookOpen className="h-5 w-5"/></span><div><p className="text-xs font-semibold uppercase tracking-wide text-green-700">Today's lesson</p><h2 className="font-display text-xl font-semibold text-ink">Juz 1 · Pages 4–6</h2><p className="mt-1 text-sm text-ink/55">Today's target: 1 page (16 lines)</p></div></div><Button onClick={()=>navigate('/student/lesson')}>Start lesson <ArrowRight className="ml-2 h-4 w-4"/></Button></CardContent></Card>
 <div className="grid gap-4 md:grid-cols-2"><Card><CardTitle className="mb-4">This week's scores</CardTitle><ResponsiveContainer width="100%" height={280}><BarChart data={WEEK_SCORES}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Bar dataKey="score" fill="#2F6B4F" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Card><Card><CardTitle className="mb-4">Progress milestones</CardTitle><CardContent className="space-y-4">{milestones.map(m=><div key={m.name}><div className="flex justify-between text-sm"><span className="font-medium">{m.name}</span><span className="text-ink/50">Est. {m.projectedDate}</span></div><div className="mt-2 h-2 rounded-full bg-line"><div className="h-full rounded-full bg-green-600" style={{width:`${Math.min(quranComplete/m.percentage*100,100)}%`}}/></div></div>)}<button onClick={()=>navigate('/student/calendar')} className="inline-flex items-center gap-1 text-sm font-medium text-green-700"><CalendarDays className="h-4 w-4"/>View full calendar</button></CardContent></Card></div></div>
}
