import { useEffect, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { Mail, CheckCircle2 } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { useToast } from '@/components/ui/Toaster'

export function VerifyEmail() { const [params] = useSearchParams(); const navigate = useNavigate(); const { push } = useToast(); const [verified,setVerified]=useState(false); const email=params.get('email') || 'your email address'; useEffect(()=>{if(params.get('token')) {const t=setTimeout(()=>setVerified(true),600); const r=setTimeout(()=>navigate('/teacher'),2600); return ()=>{clearTimeout(t);clearTimeout(r)}}},[params,navigate]); return <div className="mx-auto flex min-h-screen max-w-md items-center px-4"><div className="w-full rounded-lg border border-line bg-white p-8 text-center shadow-sm">{params.get('token')&&!verified?<><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-paper-dim border-t-green-600"/><h1 className="mt-5 font-display text-2xl font-semibold text-ink">Verifying…</h1></>:<>{verified?<CheckCircle2 className="mx-auto h-12 w-12 text-green-700"/>:<Mail className="mx-auto h-12 w-12 text-green-700"/>}<h1 className="mt-4 font-display text-2xl font-semibold text-ink">{verified?'Email verified!':'Check your email'}</h1><p className="mt-2 text-sm text-ink/55">{verified?'Redirecting to dashboard…':<>We sent a verification link to {email}.</>}</p>{!verified&&<><Button className="mt-6 w-full" onClick={()=>push('Verification email sent')}>Resend email</Button><Link className="mt-4 block text-sm text-green-700" to="/signup">Change email</Link></>}</>}</div></div> }

export function ForgotPassword() { const [email,setEmail]=useState(''); const [sent,setSent]=useState(false); const {push}=useToast(); const submit=()=>{if(!/^\S+@\S+\.\S+$/.test(email)){push('Enter a valid email address');return} setSent(true);push('Reset link sent')}; return <div className="mx-auto flex min-h-screen max-w-md items-center px-4"><div className="w-full rounded-lg border border-line bg-white p-8 shadow-sm"><h1 className="font-display text-2xl font-semibold text-ink">Reset your password</h1>{sent?<p className="mt-3 text-sm text-ink/55">Check your email for a password reset link.</p>:<><label className="mt-5 block text-sm font-medium text-ink">Email</label><Input value={email} onChange={e=>setEmail(e.target.value)} type="email" className="mt-1"/><Button className="mt-5 w-full" onClick={submit}>Send reset link</Button></>}<Link to="/login" className="mt-4 block text-center text-sm text-green-700">Back to login</Link></div></div> }

export function ResetPassword() { const navigate=useNavigate(); const {push}=useToast(); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const score=(password.length>=12?3:password.length>=8?2:1)+( /[A-Z]/.test(password)&&/[0-9]/.test(password)?1:0); const label=score>=3?'Strong':score===2?'Fair':'Weak'; const submit=()=>{if(password.length<8){push('Use at least 8 characters');return}if(password!==confirm){push('Passwords do not match');return}push('Password updated');setTimeout(()=>navigate('/login'),1200)}; return <div className="mx-auto flex min-h-screen max-w-md items-center px-4"><div className="w-full rounded-lg border border-line bg-white p-8 shadow-sm"><h1 className="font-display text-2xl font-semibold text-ink">Choose a new password</h1><label className="mt-5 block text-sm font-medium text-ink">New password</label><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1"/><div className="mt-2 h-1.5 rounded-full bg-paper-dim"><div className="h-full rounded-full bg-green-600" style={{width:`${Math.min(100,score*25)}%`}}/></div><p className="mt-1 text-xs text-ink/55">Strength: {label}</p><label className="mt-4 block text-sm font-medium text-ink">Confirm password</label><Input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-1"/><Button className="mt-5 w-full" onClick={submit}>Reset password</Button></div></div> }
