import { useState } from 'react'
import { addDays, format } from 'date-fns'
import { Modal } from '@/components/ui/Modal'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { useAppStore } from '@/lib/store'
import { today } from '@/lib/mockData'
import { useToast } from '@/components/ui/Toaster'
export type ScheduledSession={id:string;date:string;time:string;duration:number;studentName:string;className:string;lessonTitle:string;meetUrl:string}
export function ScheduleSessionModal({open,onClose,onScheduled}:{open:boolean;onClose:()=>void;onScheduled:(session:ScheduledSession)=>void}){const{classes}=useAppStore();const{push}=useToast();const[classId,setClassId]=useState('');const[date,setDate]=useState(format(addDays(today,1),'yyyy-MM-dd'));const[time,setTime]=useState('15:00');const[duration,setDuration]=useState(45);const[lesson,setLesson]=useState('');const[meetUrl,setMeetUrl]=useState('');const[saving,setSaving]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!classId||!date||!time){push('Please complete the required fields');return}setSaving(true);await new Promise(r=>setTimeout(r,500));const room=classes.find(c=>c.id===classId);onScheduled({id:`scheduled-${Date.now()}`,date,time,duration,studentName:'Class session',className:room?.name??'Class',lessonTitle:lesson||'Lesson to be confirmed',meetUrl:meetUrl||'https://meet.google.com/abc-defg-hij'});setSaving(false);push(`Session scheduled for ${format(new Date(`${date}T${time}`),'EEE, MMM d, h:mm a')}`);onClose()};return <Modal open={open} onClose={onClose} title="Schedule session"><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">Class<select value={classId} onChange={e=>setClassId(e.target.value)} className="mt-1 w-full rounded-md border border-line bg-paper px-3 py-2"><option value="">Select a class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Date<Input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1"/></label><label className="text-sm font-medium">Time<Input type="time" value={time} onChange={e=>setTime(e.target.value)} className="mt-1"/></label></div><label className="block text-sm font-medium">Duration<select value={duration} onChange={e=>setDuration(Number(e.target.value))} className="mt-1 w-full rounded-md border border-line bg-paper px-3 py-2">{[30,45,60,90].map(n=><option key={n} value={n}>{n} min</option>)}</select></label><label className="block text-sm font-medium">Lesson / topic<Input value={lesson} onChange={e=>setLesson(e.target.value)} placeholder="e.g. Juz 1, Pages 4–6" className="mt-1"/></label><label className="block text-sm font-medium">Google Meet link<Input value={meetUrl} onChange={e=>setMeetUrl(e.target.value)} placeholder="Paste your Meet link" className="mt-1"/><span className="mt-1 block text-xs text-ink/45">Or leave blank — you can add it later.</span></label><div className="flex justify-end gap-3 pt-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={saving}>{saving?'Scheduling…':'Schedule session'}</Button></div></form></Modal>}
